<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
</head>

<?php
    session_start();
    if(!isset($_SESSION["email"]))
    {
        header("AuthError.php");
        die();
    }
$um=$_SESSION["email"];
$ut=$_SESSION["usertype"];
if($ut!="user")
{
    header("AuthError.php");
    die();
}
?>
 
<?php $apikey="rzp_test_e8YTsVPImO2XWt"; 

$ph=$_POST["ph"];
$mn=$_POST["mn"];
$pr=$_POST["pr"];
$em=$_POST["em"];
$mid=$_POST["mid"];

$fn=$_POST["fn"];
$ln=$_POST["ln"];
$cn=$_POST["cn"];
$adr=$_POST["adr"];
$pin=$_POST["pin"];
$cit=$_POST["cit"];
$st=$_POST["st"];
$um=$_POST["um"];

?>

<form action="https://www.example.com/payment/success/" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apikey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $pr * 100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END'; ?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay "
    data-name="<?php echo $mn; ?>"
    data-description=""
    data-image="../medical/photos/<?php echo $ph;?>"
    data-prefill.name="<?php echo $fn;echo $ln; ?>"
    data-prefill.email="<?php echo $um; ?>"
	data-prefill.contact="<?php echo $cn; ?>"
	data-prefill.address="<?php echo $adr; ?>"
    data-theme.color="green"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>

 <body>
</body>
</html>