<?php
    session_start();
    if(!isset($_SESSION["email"]))
    {
        header("location:../AuthError.php");
        die();
    }
$e1=$_SESSION["email"];
$ut=$_SESSION["usertype"];
if($ut!="user")
{
    header("location:../AuthError.php");
    die();
}
?>
<?php include("u1.php");?>

<?php $apikey="rzp_test_e8YTsVPImO2XWt"; 

$pp=$_POST["pp"];
$pn=$_POST["pn"];
$pr=$_POST["pr"];
$em=$_POST["em"];
$pid=$_POST["pid"];

$fn=$_POST["fn"];
$ln=$_POST["ln"];
$cn=$_POST["cn"];
$adr=$_POST["adr"];
$pin=$_POST["pin"];
$cit=$_POST["cit"];
$st=$_POST["st"];
$ue=$_POST["ue"];

?>

<form action="https://www.example.com/payment/success/" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apikey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $pr * 100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END'; ?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="<?php echo $pn; ?>"
    data-description=""
    data-image="../seller/product_photos/<?php echo $pp;?>"
    data-prefill.name="<?php echo $fn;echo $ln; ?>"
    data-prefill.email="<?php echo $ue; ?>"
	data-prefill.contact="<?php echo $cn; ?>"
	data-prefill.address="<?php echo $adr; ?>"
    data-theme.color="blue"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>

<?php include("u2.php");?>